### ISSUE TITLE
Not an issue, but a suggestion

### ISSUE THREAD

**Issue by OrionRandD** [rswgnu/hyperbole#19]
I have tried to use hycontrol-frame(window).
This is a great tool.
But, perhaps vim-evil key-binds could be added as options
to the default frame-windows control.
It is a little confusing for people to think about other keys
to memorize that uses some vim letters as hycontrol movements and such.
Just a suggestion

**Comment by rswgnu** [comment]
Not sure how we could accommodate this.  Hyperbole defaults to Emacs-like key bindings and otherwise, you have to bind keys yourself.  If someone wanted to support vim bindings, they would have to do it across Hyperbole's functionality for us to consider integrating it and I don't see that happening anytime soon.
