### ISSUE TITLE
More than one entry in the load-path

### ISSUE THREAD

**Issue by doolio** [rswgnu/hyperbole#23]
I manage my Emacs config in a dotfiles repository and use GNU Stow to sym link to my home directory (i.e. ~/.emacs.d -> ~/dotfiles/emacs/dot-emacs.d/). I don't believe I'm unique in this approach but maybe amongst users that want to use hyperbole. When I install packages they are installed to:

`/home/doolio/dotfiles/emacs/dot-emacs.d/elpa/`

so for hyperbole it is:

`/home/doolio/dotfiles/emacs/dot-emacs.d/elpa/hyperbole-7.0.6/`

However, I then have the following entries in my `load-path`:

`"/home/doolio/dotfiles/emacs/dot-emacs.d/elpa/hyperbole-7.0.6/kotl/" "/home/doolio/dotfiles/emacs/dot-emacs.d/elpa/hyperbole-7.0.6/" "/home/doolio/.emacs.d/elpa/hyperbole-7.0.6"`

whereas for any other package only a single entry of the form exists:

`"/home/doolio/.emacs.d/elpa/<package-name>"`

so it seems in general the `load-path` uses the symbolic link paths. But you can see for hyperbole the `load-path` is set with the symbolic link and physical paths. There is also a physical path entry for the kotl subdirectory. I don't understand why this happens and only does so for hyperbole. I'm having issues with hyperbole (e.g. buttons not working) and I want to rule this out as the cause. 

Is it expected to have the kotl subdirectory added to the `load-path`? I presume so and I presume it exists in the first place for your own code organisation reasons. Reading the info manual (elisp)Library Search it seems subdirectories can be automatically added to the path if a subdirs.el file exists in the parent directory but it doesn't exist for hyperbole.

Thanks for your time and hyperbole.

Edit: Correct some typesetting.

**Comment by rswgnu** [comment]
Good point, we will have a look.

-- Bob

**Comment by rswgnu** [comment]
In hpath-load.el, we have these lines which explain why the fully resolved hyperbole load-path is being added, so we'll have to add a check for the symlink version of the path as well:

;; Ensure final name (after resolving all links) of hyperb:dir is
;; used; otherwise, Hyperbole may fail to substitute this as a
;; variable into link path buttons.
(when (stringp hyperb:dir)
  (setq hyperb:dir (file-truename hyperb:dir)))

;; Add hyperb:dir to load-path so other Hyperbole libraries can be
;; found unless it is already there since the Emacs Package Manager
;; may have already added it.
(unless (member (directory-file-name hyperb:dir) load-path)
  (add-to-list 'load-path hyperb:dir))

**Comment by rswgnu** [comment]
Try reversing the order of the two sections of code from above in hload-path.el and see if that resolves your symlink problem.  I think that will work at least for the root-level Hyperbole directory.  the kotl directory would still be added using the fully resolved path.

**Comment by rswgnu** [comment]
This should be fixed if you pull the master branch from here and run that when you startup Emacs.
