### ISSUE TITLE
Implicit button `M-x` doesn't work with `helm-M-x`

### ISSUE THREAD

**Issue by xueeinstein** [rswgnu/hyperbole#36]
As a helm user, I rebind `M-x` to `helm-M-x`. Unfortunately, the implicit button executing `M-x xxx` doesn't work well. Please see the following gif.

![hyperbole](https://user-images.githubusercontent.com/3424201/91635526-ce11fc80-ea2b-11ea-92d2-eb819d1c1a48.gif)

**Comment by matsl** [comment]
Hi, thanks for the report.

I can confirm that this is a problem for helm users. It raises the general question of how key series buttons shall behave when the user binds keys to none standard values and in particular use completion packages that provides suggestions. Since helms functionality kicks in when binding M-x the key series does not work as you would expect. The best thing Hyperbole can do is to try to disable helm while executing a key series button. With the idea to fall back to standard Emacs behaviour in the key series button avoiding user customization.

However Helm does not have a simple way to temporarily disable its functionality. So it has proven hard do to this. Bob has made efforts to disable helm-M-x which makes this go a bit further. However the problem is not solved by that completely. There is more helm functionality that interferes in bad way with the key series button even after solving M-x.

Similar problems exists when using completion packages such as ivy.

**Comment by rswgnu** [comment]
I thought we had fixed this for helm.  M-x in a key series should use its standard binding if I recall.  Did you report your Hyperbole version number?

-- Bob

**Comment by xueeinstein** [comment]
@rswgnu @matsl Thanks for your reply! Previously I was using 7.1.2 from GNU Elpa. After upgrading to 7.1.3 from Github, M-x works perfectly!
